#ifndef OPENGL_MANAGEMENT_EXCEPTIONS
#define OPENGL_MANAGEMENT_EXCEPTIONS
namespace OPENGL_management {
    enum Exception{
        WINDOW_NOT_ACTIVE,
        WINDOW_NOT_CLOSED,
        INVALID_UNIFORM_TYPE,
        INVALID_INPUT_TYPE,
        INVALID_TYPE,
        INPUT_TYPE_NOT_FOUND,
        MATCHING_UNIFORM_SLOT_NOT_FOUND,
        SHADER_MISSING_UNIFORM_SLOT,
        MODEL_NOT_FOUND,
        TEXTURE2D_NOT_FOUND,
        SHADER_NOT_FOUND,
        INVALID_DEFAULT_CODE
    };
}

#endif