#ifndef PLUSHUTILEXCEPTION_HPP
#define PLUSHUTILEXCEPTION_HPP

namespace PlushUtil {
    enum class PlushUtilException{
        CANNOT_CREATE_NULL_MANAGED_OBJECT,
        CANNOT_MOVE_ASSIGN_ORIGINAL_INTO_CLONE,
        CANNOT_MOVE_ASSIGN_CLONE_INTO_ORIGINAL,
        CANNOT_COPY_ORIGINAL_MANAGED_OBJECT,
        CANNOT_COPY_ASSIGN_INTO_ORIGINAL_MANAGED_OBJECT,
        MANAGED_OBJECT_EXPIRED,
        FILE_READ_ERROR,
        ITEM_NOT_LOADED_IN_REGISTRY,
        CANNOT_ACCESS_EMPTY_SLOT
    };

    void describeException(PlushUtilException e);
}

#endif // PLUSHUTILEXCEPTION_HPP
