#ifndef PLUSHUTILEXCEPTION_HPP
#define PLUSHUTILEXCEPTION_HPP

enum class Exception{
    CANNOT_CREATE_NULL_MANAGED_OBJECT,
    CANNOT_MOVE_ASSIGN_ORIGINAL_INTO_CLONE,
    CANNOT_MOVE_ASSIGN_CLONE_INTO_ORIGINAL,
    CANNOT_COPY_ORIGINAL_MANAGED_OBJECT,
    CANNOT_COPY_INTO_ORIGINAL_MANAGED_OBJECT
};

#endif // PLUSHUTILEXCEPTION_HPP
